version: '3.4'

services:
  deeplearningservice:
    image: deeplearningservice
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 5002:5002