apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeplearningservice-deployment
  labels:
    app: deeplearningservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeplearningservice-deployment
  template:
    metadata:
      labels:
        app: deeplearningservice-deployment
    spec:
      containers:
      - name: deeplearningservice-app
        image: salmanad01/rfid-deeplearningservice:latest
        imagePullPolicy: Always
        env:
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: deeplearningservice-secret
                key: ACCESS_TOKEN
        ports:
        - containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: deeplearningservice-service
spec:
  type: LoadBalancer
  selector:
    app: deeplearningservice-deployment
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002